// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTodo(arg1:string,arg2:number):Promise<main.TodoEntry>;

export function DeleteTodo(arg1:number):Promise<main.TodoEntry>;

export function GetAllTodos():Promise<Array<main.TodoEntry>>;

export function Greet(arg1:string):Promise<string>;
