// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
