// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1, arg2) {
  return window['go']['main']['App']['CreateTodo'](arg1, arg2);
}

export function DeletePermanently(arg1) {
  return window['go']['main']['App']['DeletePermanently'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function GetDeleted() {
  return window['go']['main']['App']['GetDeleted']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateCompleted(arg1, arg2) {
  return window['go']['main']['App']['UpdateCompleted'](arg1, arg2);
}
